# Generated by Django 4.0.1 on 2022-07-21 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link_shortener', '0002_rename_data_link_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='link',
            name='following_count',
            field=models.IntegerField(default=0, verbose_name='Количество переходов'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=300, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_creator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.URLField(max_length=20, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
