# Generated by Django 4.0.1 on 2022-07-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0004_alter_link_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='original_link',
        ),
    ]
