# Generated by Django 4.0.1 on 2022-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0008_link_following_date_alter_link_original_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='following_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество переходов'),
        ),
        migrations.AlterField(
            model_name='link',
            name='following_date',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего перехода'),
        ),
    ]
